
functional:
  - Пользователь должен иметь возможность создать игру с другим пользователем 
  - Пользователь должен иметь возможность видеть написание кода друг у друга
  - Пользователь должен иметь возможность играть с другом по ссылке
  - Пользователь должен иметь возможность создать игру ботом
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность авторизоваться
  - Пользователь должен иметь возможность просматривать рейтинг игроков
  - Пользователь должен иметь возможность получать сообщения в чате
  - Пользователь должен иметь возможность видеть задачу
  - Пользователь должен иметь возможность видеть результат
  - Пользователь должен иметь возможность получать сообщения в чате
  - Пользователь должен иметь возможность выбора языка
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Пользователь должен иметь возможность за матчем других игроков

